/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialog;

import Windows.OrdersWindow;
import javax.swing.JOptionPane;
import sisexpsql.DBcustomers;
import sisexpsql.DBemployees;

/**
 *
 * @author Luna
 */
public class EditCustomerDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditCustomerDialog
     */
    public EditCustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        customerNumberTextField.setText(OrdersWindow.text);
        saleRepEmployeeNumberComboBox.setModel(new DBemployees().getEmployeesNumber());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        customerNumberTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        contactLastNameTextField = new javax.swing.JTextField();
        contactFirstNameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        addressLine1TextField = new javax.swing.JTextField();
        addressLine2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        postalCodeTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        creditLimitTextField = new javax.swing.JTextField();
        saleRepEmployeeNumberComboBox = new javax.swing.JComboBox<>();
        customerNameButton = new javax.swing.JButton();
        contactLastNameButton = new javax.swing.JButton();
        contactFirstNameButton = new javax.swing.JButton();
        phoneButton = new javax.swing.JButton();
        addressLine1Button = new javax.swing.JButton();
        addressLine2Button = new javax.swing.JButton();
        cityButton = new javax.swing.JButton();
        stateButton = new javax.swing.JButton();
        postalCodeButton = new javax.swing.JButton();
        countryButton = new javax.swing.JButton();
        saleRepEmployeeNumberButton = new javax.swing.JButton();
        creditLimitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar un Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modificar Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Número de Cliente:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre del Cliente:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Apellido del Contacto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nombre del Contacto:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Número de Teléfono:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Dirección:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Dirección alternativa (opcional:)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Ciudad:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Provincia (opcional):");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Código Postal (opcional):");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("País:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Número de Empleado a cargo:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Límite de Credito (opcional):");

        customerNumberTextField.setEditable(false);

        contactLastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactLastNameTextFieldKeyTyped(evt);
            }
        });

        contactFirstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactFirstNameTextFieldKeyTyped(evt);
            }
        });

        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyTyped(evt);
            }
        });

        cityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityTextFieldKeyTyped(evt);
            }
        });

        stateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stateTextFieldKeyTyped(evt);
            }
        });

        postalCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postalCodeTextFieldKeyTyped(evt);
            }
        });

        countryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryTextFieldKeyTyped(evt);
            }
        });

        creditLimitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditLimitTextFieldKeyTyped(evt);
            }
        });

        saleRepEmployeeNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        customerNameButton.setText("Modificar Nombre de Cliente");
        customerNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameButtonActionPerformed(evt);
            }
        });

        contactLastNameButton.setText("Modificar Apellido");
        contactLastNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactLastNameButtonActionPerformed(evt);
            }
        });

        contactFirstNameButton.setText("Modificar Nombre");
        contactFirstNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFirstNameButtonActionPerformed(evt);
            }
        });

        phoneButton.setText("Modificar Teléfono");
        phoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneButtonActionPerformed(evt);
            }
        });

        addressLine1Button.setText("Modificar Dirección");
        addressLine1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1ButtonActionPerformed(evt);
            }
        });

        addressLine2Button.setText("Modificar Dirección Alternativa");
        addressLine2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine2ButtonActionPerformed(evt);
            }
        });

        cityButton.setText("Modificar Ciudad");
        cityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityButtonActionPerformed(evt);
            }
        });

        stateButton.setText("Modificar Provincia");
        stateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateButtonActionPerformed(evt);
            }
        });

        postalCodeButton.setText("Modificar Código Postal");
        postalCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postalCodeButtonActionPerformed(evt);
            }
        });

        countryButton.setText("Modificar País");
        countryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryButtonActionPerformed(evt);
            }
        });

        saleRepEmployeeNumberButton.setText("Cambiar Empleado");
        saleRepEmployeeNumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleRepEmployeeNumberButtonActionPerformed(evt);
            }
        });

        creditLimitButton.setText("Modificar Límite de Credito");
        creditLimitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditLimitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNumberTextField)
                            .addComponent(customerNameTextField)
                            .addComponent(contactLastNameTextField)
                            .addComponent(contactFirstNameTextField)
                            .addComponent(phoneTextField)
                            .addComponent(addressLine1TextField)
                            .addComponent(addressLine2TextField)
                            .addComponent(cityTextField)
                            .addComponent(stateTextField)
                            .addComponent(postalCodeTextField)
                            .addComponent(countryTextField)
                            .addComponent(creditLimitTextField)
                            .addComponent(saleRepEmployeeNumberComboBox, 0, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contactLastNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contactFirstNameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phoneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLine1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLine2Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(postalCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(countryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saleRepEmployeeNumberButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creditLimitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(customerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contactLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLastNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contactFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactFirstNameButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine1Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(addressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine2Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityButton))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(postalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalCodeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(saleRepEmployeeNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleRepEmployeeNumberButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(creditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditLimitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameButtonActionPerformed
        if(customerNameTextField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateCustomerName(customerNameTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_customerNameButtonActionPerformed

    private void contactLastNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactLastNameButtonActionPerformed
        if (contactLastNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Apellido.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateContactLastName(contactLastNameTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_contactLastNameButtonActionPerformed

    private void contactFirstNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFirstNameButtonActionPerformed
        if (contactFirstNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateContactFirstName(contactFirstNameTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_contactFirstNameButtonActionPerformed

    private void phoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneButtonActionPerformed
        if (phoneTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un número de teléfono.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updatePhone(phoneTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_phoneButtonActionPerformed

    private void addressLine1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1ButtonActionPerformed
        if (addressLine1TextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una Dirección.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateAddressLine1(addressLine1TextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_addressLine1ButtonActionPerformed

    private void addressLine2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine2ButtonActionPerformed
        DBcustomers db = new DBcustomers();
        db.updateAddressLine2(addressLine2TextField.getText(), customerNumberTextField.getText());
        JOptionPane.showMessageDialog(null, "Modificado Correctamente");
    }//GEN-LAST:event_addressLine2ButtonActionPerformed

    private void cityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityButtonActionPerformed
        if (cityTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una ciudad.");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateCity(cityTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_cityButtonActionPerformed

    private void stateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateButtonActionPerformed
        DBcustomers db = new DBcustomers();
        db.updateState(stateTextField.getText(), customerNumberTextField.getText());
        JOptionPane.showMessageDialog(null, "Modificado Correctamente");
    }//GEN-LAST:event_stateButtonActionPerformed

    private void postalCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postalCodeButtonActionPerformed
        DBcustomers db = new DBcustomers();
        db.updatePostalCode(postalCodeTextField.getText(), customerNumberTextField.getText());
        JOptionPane.showMessageDialog(null, "Modificado Correctamente");
    }//GEN-LAST:event_postalCodeButtonActionPerformed

    private void countryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryButtonActionPerformed
        if (countryTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un .");
        } else {
            DBcustomers db = new DBcustomers();
            db.updateCounrty(countryTextField.getText(), customerNumberTextField.getText());
            JOptionPane.showMessageDialog(null, "Modificado Correctamente");
        }
    }//GEN-LAST:event_countryButtonActionPerformed

    private void creditLimitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditLimitButtonActionPerformed
        DBcustomers db = new DBcustomers();
        db.updateCreditLimit(creditLimitTextField.getText(), customerNumberTextField.getText());
        JOptionPane.showMessageDialog(null, "Modificado Correctamente");
    }//GEN-LAST:event_creditLimitButtonActionPerformed

    private void saleRepEmployeeNumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleRepEmployeeNumberButtonActionPerformed
        DBcustomers db = new DBcustomers();
        db.updateSalesRepEmployeeNumber(saleRepEmployeeNumberComboBox.getSelectedItem().toString(), 
                                        customerNumberTextField.getText());
        JOptionPane.showMessageDialog(null, "Modificado Correctamente");
    }//GEN-LAST:event_saleRepEmployeeNumberButtonActionPerformed

    private void contactLastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactLastNameTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_contactLastNameTextFieldKeyTyped

    private void contactFirstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactFirstNameTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_contactFirstNameTextFieldKeyTyped

    private void phoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') && !(evt.getKeyChar() == '+')){
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextFieldKeyTyped

    private void cityTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_cityTextFieldKeyTyped

    private void stateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_stateTextFieldKeyTyped

    private void postalCodeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postalCodeTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') &&
                !(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') &&
                !(evt.getKeyChar() == '-') && !(evt.getKeyChar() == ' ')){
            evt.consume();
        }
    }//GEN-LAST:event_postalCodeTextFieldKeyTyped

    private void countryTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_countryTextFieldKeyTyped

    private void creditLimitTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditLimitTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') && !(evt.getKeyChar() == '.')){
            evt.consume();
        }
    }//GEN-LAST:event_creditLimitTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditCustomerDialog dialog = new EditCustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addressLine1Button;
    private javax.swing.JTextField addressLine1TextField;
    private javax.swing.JButton addressLine2Button;
    private javax.swing.JTextField addressLine2TextField;
    private javax.swing.JButton cityButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton contactFirstNameButton;
    private javax.swing.JTextField contactFirstNameTextField;
    private javax.swing.JButton contactLastNameButton;
    private javax.swing.JTextField contactLastNameTextField;
    private javax.swing.JButton countryButton;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JButton creditLimitButton;
    private javax.swing.JTextField creditLimitTextField;
    private javax.swing.JButton customerNameButton;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField customerNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton phoneButton;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton postalCodeButton;
    private javax.swing.JTextField postalCodeTextField;
    private javax.swing.JButton saleRepEmployeeNumberButton;
    private javax.swing.JComboBox<String> saleRepEmployeeNumberComboBox;
    private javax.swing.JButton stateButton;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables
}
