/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Windows;

import java.awt.desktop.QuitEvent;
import javax.swing.JOptionPane;
import sisexpsql.DBcustomers;
import sisexpsql.DBemployees;

/**
 *
 * @author Luna
 */
public class addCustomer extends javax.swing.JFrame {

    /**
     * Creates new form addCustomer
     */
    public addCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
        DBemployees db = new DBemployees();
        salesRepEmployeeNumberComboBox.setModel(db.getEmployeesNumber());
    }
    public boolean validateTextFields(){
        
        if(customerNumberTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Número de Cliente");
            return false;
        }
        
        if (customerNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nombre de Cliente");
            return false;
        }
        
        if (contactLastNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Apellido del Contacto");
            return false;
        }
        
        if (contactFirstNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nombre del Contacto");
            return false;
        }
        
        if (phoneTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Teléfono");
            return false;
        }
        
        if (addressLine1TextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una Dirección");
            return false;
        }
        
        if (cityTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar una Ciudad");
            return false;
        }
        
        if (phoneTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Teléfono");
            return false;
        }
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        customerNumberTextField = new javax.swing.JTextField();
        customerNameTextField = new javax.swing.JTextField();
        contactLastNameTextField = new javax.swing.JTextField();
        contactFirstNameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        addressLine1TextField = new javax.swing.JTextField();
        addressLine2TextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        postalCodeTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        creditLimitTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        salesRepEmployeeNumberComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Añadir Cliente");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Número de Cliente:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nombre del Cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Apellido del Contacto:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre del Contacto:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Número de Teléfono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Dirección alternativa (opcional:)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Ciudad:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Provincia (opcional):");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Código Postal (opcional):");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("País:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Número de Empleado a cargo:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Límite de Credito (opcional):");

        customerNumberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerNumberTextFieldKeyTyped(evt);
            }
        });

        customerNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                customerNameTextFieldKeyTyped(evt);
            }
        });

        contactLastNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactLastNameTextFieldKeyTyped(evt);
            }
        });

        contactFirstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactFirstNameTextFieldKeyTyped(evt);
            }
        });

        phoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneTextFieldKeyTyped(evt);
            }
        });

        cityTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityTextFieldKeyTyped(evt);
            }
        });

        stateTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stateTextFieldKeyTyped(evt);
            }
        });

        postalCodeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                postalCodeTextFieldKeyTyped(evt);
            }
        });

        countryTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryTextFieldKeyTyped(evt);
            }
        });

        creditLimitTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                creditLimitTextFieldKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        salesRepEmployeeNumberComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customerNumberTextField)
                            .addComponent(customerNameTextField)
                            .addComponent(contactLastNameTextField)
                            .addComponent(contactFirstNameTextField)
                            .addComponent(phoneTextField)
                            .addComponent(addressLine1TextField)
                            .addComponent(addressLine2TextField)
                            .addComponent(cityTextField)
                            .addComponent(stateTextField)
                            .addComponent(postalCodeTextField)
                            .addComponent(countryTextField)
                            .addComponent(creditLimitTextField)
                            .addComponent(salesRepEmployeeNumberComboBox, 0, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(contactLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contactFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(addressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(postalCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(countryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jButton1)
                            .addComponent(creditLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(salesRepEmployeeNumberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validateTextFields()){
            DBcustomers db = new DBcustomers();
            db.addCustomer(customerNumberTextField.getText(), customerNameTextField.getText(), 
                contactLastNameTextField.getText(), contactFirstNameTextField.getText(),
                phoneTextField.getText(), addressLine1TextField.getText(), 
                addressLine2TextField.getText(), cityTextField.getText(),
                stateTextField.getText(), postalCodeTextField.getText(), 
                countryTextField.getText(), salesRepEmployeeNumberComboBox.getSelectedItem().toString(),
                creditLimitTextField.getText());
            JOptionPane.showMessageDialog(null, "Cargado Correctamente");
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerNumberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNumberTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_customerNumberTextFieldKeyTyped

    private void customerNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customerNameTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_customerNameTextFieldKeyTyped

    private void contactLastNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactLastNameTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_contactLastNameTextFieldKeyTyped

    private void contactFirstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactFirstNameTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_contactFirstNameTextFieldKeyTyped

    private void phoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') && !(evt.getKeyChar() == '+')){
            evt.consume();
        }
    }//GEN-LAST:event_phoneTextFieldKeyTyped

    private void cityTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_cityTextFieldKeyTyped

    private void stateTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stateTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_stateTextFieldKeyTyped

    private void postalCodeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_postalCodeTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')){
            evt.consume();
        }
    }//GEN-LAST:event_postalCodeTextFieldKeyTyped

    private void countryTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryTextFieldKeyTyped
        if (!(evt.getKeyChar() >= 'A' && evt.getKeyChar() <= 'Z') && 
                !(evt.getKeyChar() >= 'a' && evt.getKeyChar() <= 'z') &&
                !(evt.getKeyChar() == ' ') && !(evt.getKeyChar() == 'á') && 
                !(evt.getKeyChar() == 'é') && !(evt.getKeyChar() == 'í') && 
                !(evt.getKeyChar() == 'ó') && !(evt.getKeyChar() == 'ú')){
            evt.consume();
        }
    }//GEN-LAST:event_countryTextFieldKeyTyped

    private void creditLimitTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditLimitTextFieldKeyTyped
        if (!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') && !(evt.getKeyChar() == '.')){
            evt.consume();
        }
    }//GEN-LAST:event_creditLimitTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressLine1TextField;
    private javax.swing.JTextField addressLine2TextField;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JTextField contactFirstNameTextField;
    private javax.swing.JTextField contactLastNameTextField;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField creditLimitTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JTextField customerNumberTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField postalCodeTextField;
    private javax.swing.JComboBox<String> salesRepEmployeeNumberComboBox;
    private javax.swing.JTextField stateTextField;
    // End of variables declaration//GEN-END:variables
}
